---
- name: Create the configuration directory
  ansible.builtin.file:
    path: /etc/invio
    state: directory
    owner: root
    group: "{{ invio_group }}"
    mode: "0750"

- name: Write the env file
  ansible.builtin.template:
    src: invio.env.j2
    dest: /etc/invio/invio.env
    owner: root
    group: "{{ invio_group }}"
    mode: "0640"
  no_log: true
